# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'helix_poc_proj'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'
#profile: 'default'
#profile: 'helix'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
log-path: "logs"

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  'helix_poc_proj':
    staging:
      +materialized: table
      +transient: false
      +database: 'DA_HELIX_DB_TEST'
    bronze:
      +materialized: table
      +transient: false
      +database: 'DA_HELIX_DB_TEST'
    silver:
      +materialized: table
      +transient: false
      +database: 'DA_HELIX_DB_TEST'

vars:
  database: 'DA_HELIX_DB_TEST'
  raw_schema: 'HELIX_RAW'
  bronze_schema: 'HELIX_STG'
  silver_schema: 'HELIX_CDW'
  audit_schema: 'HELIX_AUDIT'

# {{ generate_schema_name() }}

snapshots:
  +transient: false
  'helix_poc_proj':
    +post-hook:
      - " {{ insert_audit_log_record() }} "
  
on-run-start:
  - " {{ create_audit_log_table() }}"